import os
import tempfile
from app.services.storage_service import StorageService
from app.utils.logger import get_logger
from app.utils.errors import StorageError
from jinja2 import Template

logger = get_logger(__name__)


class PDFService:
    def __init__(self):
        self.storage = StorageService()
        template_path = os.path.join(os.path.dirname(__file__), "..", "templates", "sow_template.html")
        try:
            with open(template_path, "r", encoding="utf-8") as f:
                self.template = Template(f.read())
        except Exception:
            self.template = Template(self._default_template())

    def _default_template(self) -> str:
        return """<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
h1 { color: #1a1a2e; border-bottom: 2px solid #16213e; padding-bottom: 8px; }
h2 { color: #16213e; margin-top: 24px; }
p, li { font-size: 14px; line-height: 1.6; }
.header { text-align: center; margin-bottom: 40px; }
.section { margin-bottom: 24px; }
.risk-box { background: #fff3cd; border-left: 4px solid #ffc107; padding: 12px; margin: 8px 0; }
.footer { margin-top: 60px; font-size: 12px; color: #666; text-align: center; }
</style>
</head>
<body>
<div class="header">
<h1>Statement of Work</h1>
<p><strong>Client:</strong> {{ client_name }} | <strong>Project:</strong> {{ project_name }}</p>
<p><strong>Industry:</strong> {{ industry }}</p>
</div>
<div class="section">
<h2>Project Overview</h2>
<p>{{ content.project_overview }}</p>
</div>
<div class="section">
<h2>Objectives</h2>
<ul>{% for o in content.objectives %}<li>{{ o }}</li>{% endfor %}</ul>
</div>
<div class="section">
<h2>Scope of Work</h2>
<ul>{% for s in content.scope_of_work %}<li>{{ s }}</li>{% endfor %}</ul>
</div>
<div class="section">
<h2>Deliverables</h2>
<ul>{% for d in content.deliverables %}<li>{{ d }}</li>{% endfor %}</ul>
</div>
<div class="section">
<h2>Timeline</h2>
<ul>{% for t in content.timeline %}<li>{{ t }}</li>{% endfor %}</ul>
</div>
<div class="section">
<h2>Payment Schedule</h2>
<ul>{% for p in content.payment_schedule %}<li>{{ p }}</li>{% endfor %}</ul>
</div>
<div class="section">
<h2>Client Responsibilities</h2>
<ul>{% for r in content.client_responsibilities %}<li>{{ r }}</li>{% endfor %}</ul>
</div>
<div class="section">
<h2>Revision Policy</h2>
<p>{{ content.revision_policy }}</p>
</div>
<div class="section">
<h2>Out of Scope</h2>
<ul>{% for o in content.out_of_scope %}<li>{{ o }}</li>{% endfor %}</ul>
</div>
<div class="section">
<h2>Assumptions</h2>
<ul>{% for a in content.assumptions %}<li>{{ a }}</li>{% endfor %}</ul>
</div>
<div class="section">
<h2>Acceptance Criteria</h2>
<ul>{% for a in content.acceptance_criteria %}<li>{{ a }}</li>{% endfor %}</ul>
</div>
<div class="section">
<h2>Signature Section</h2>
<p>{{ content.signature_section }}</p>
</div>
<div class="footer">
<p>Generated by BriefToScope</p>
</div>
</body>
</html>"""

    async def generate_pdf(self, sow: dict, client_name: str, project_name: str, industry: str) -> bytes:
        html = self.template.render(
            content=sow.get("content_json", {}),
            client_name=client_name,
            project_name=project_name,
            industry=industry,
        )
        try:
            from playwright.async_api import async_playwright

            async with async_playwright() as p:
                browser = await p.chromium.launch()
                page = await browser.new_page()
                await page.set_content(html)
                pdf_bytes = await page.pdf(format="A4", margin={"top": "20mm", "bottom": "20mm", "left": "15mm", "right": "15mm"})
                await browser.close()
                logger.info("[PDF] Generated via Playwright successfully")
                return pdf_bytes
        except Exception as e:
            logger.warning(f"[PDF] Playwright unavailable: {e}. Returning styled HTML fallback.")
            # Fallback: wrap in a print-friendly self-contained HTML document
            styled = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>SOW — {project_name}</title>
<style>
@page {{ size: A4; margin: 20mm 15mm; }}
body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 0; padding: 24px; color: #1a1a2e; line-height: 1.6; }}
h1 {{ color: #16213e; font-size: 26px; border-bottom: 3px solid #0f3460; padding-bottom: 10px; margin-bottom: 6px; }}
h2 {{ color: #16213e; font-size: 16px; margin-top: 22px; margin-bottom: 8px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }}
p, li {{ font-size: 12px; color: #333; }}
ul {{ margin-top: 4px; padding-left: 18px; }}
.header {{ text-align: center; margin-bottom: 30px; }}
.meta {{ font-size: 12px; color: #555; margin-top: 4px; }}
.footer {{ margin-top: 50px; font-size: 10px; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 12px; }}
</style>
</head>
<body>
{html}
</body>
</html>"""
            return styled.encode("utf-8")

    async def export_and_upload(self, sow: dict, client_name: str, project_name: str, industry: str) -> str:
        pdf_bytes = await self.generate_pdf(sow, client_name, project_name, industry)
        filename = f"sow-{sow['id']}.pdf"
        pdf_url = await self.storage.upload_pdf(sow["id"], pdf_bytes, filename)
        await self.storage.update_sow_pdf_url(sow["id"], pdf_url)
        return pdf_url
